### ISSUE TITLE
What is "portuml" file/folder?

### ISSUE THREAD

**Issue by morenopc** [rbonichon/portugol#1]
Hi Richard,

I'm trying to make some changes and (re)compile your portjs.js file to use in a logic class at http://edx.org.br/ here in Brazil. But I'm not sure what this `portugol -> /home/richard/dim0320/portuml` symbolic link means. Can you help me?

Thanks.

**Comment by rbonichon** [comment]
Hello Moreno,

This is a logical link that I created that I added by mistake with a too large commit.
I have deleted it from the repository.

Just as an added info, the js file is automatically generated from an OCaml binary: it might be tricky to change it directly. Let me know if I can help in any way so that we can work out through your needs.

Thanks for your report.

**Comment by morenopc** [comment]
Thanks
