### ISSUE TITLE
Power function and notation are not working

### ISSUE THREAD

**Issue by morenopc** [rbonichon/portugol#4]
Both `pot (x, y)` function and `x^y` power notation are not working at http://ossanha.github.io/portugol/www/

```
pot (2, 2)
[error]
Undeclared variable(s):
pot on line(s) 9 
```

```
2^2
[error]
File "", from line 9 character 7 to line 9 character 10 : Cannot convert real into inteiro 
```

**Comment by rbonichon** [comment]
pot is not the power function in portugol. At least not in VisuAlg, according to http://www.cafw.ufsm.br/~bruno/disciplinas/introd_programacao/materiais/visualg/help/funcoes.htm .
You are looking for the function exp.

The second error is more cumbersome. Could you give me the whole program ?
It seems you might be trying to assign the result of a power call to a integer variable, which I do not permit (this type conversion is not safe, and there are a lot of possible ways to round a float into an integer, none of them should be preferred).

**Comment by morenopc** [comment]
You're right in both cases. This example confuses me: https://github.com/ossanha/portugol/blob/master/tests/pot.alg and I was trying to assign the result of a power call to a integer. I tested both at http://ossanha.github.io/portugol/www/ but seems like my portugol compiler is not working properly.
Thank you, Richard.

**Comment by rbonichon** [comment]
This code
https://github.com/ossanha/portugol/blob/master/tests/pot.alg

was just an exercise in using recursion. This is a very ineffective way of computing the power of  
a real and the basic recursive definition only works for integral exponents (this is where the n: inteiro comes from).

Otherwise, VisuAlg allows to mix integers and reals if you promote integers as reals (this is mostly the same rules as in C). As it feels natural to a vast majority of students, I kept this functionality.

In this case, if x : real, 2 \* x is real two and works as 2.0 \* x. if x is the result of a call to power, the same rule applies. If you need to convert a real into an integer, use the function int, which will truncate the float/real.
